### ISSUE TITLE
SETUP NOT WORKING AT ALL

### ISSUE THREAD

**Issue by jesusalc** [chaskiq/chaskiq#901]
**Describe the bug**
Following all the instructions in a Fedora, then on a Ubuntu then on a MacOS. 
Always comes the same broken output.  IT DOES NOT WORK. And Test fail

**To Reproduce**
Steps to reproduce:
New Box
follow all instructions;
By the way you are missing the steps to reproduce the data

**Expected**
Tests should pass and 
server should appear

**Screenshots**
This is screenshot from MacOS box

**Comment by michelson** [comment]
Can you provide some error log?

**Comment by jesusalc** [comment]
```shell
Processing by HomeController#show as HTML
  Rendering layout layouts/application.html.erb
  Rendering home/show.erb within layouts/application
  Rendered home/show.erb within layouts/application (Duration: 3.5ms | Allocations: 1522)
Not delivering sessions due to an invalid api_key
  Doorkeeper::Application Load (0.9ms)  SELECT "oauth_applications".* FROM "oauth_applications" ORDER BY "oauth_applications"."id" ASC LIMIT 1
  ↳ app/views/layouts/application.html.erb:18
  Rendered layout layouts/application.html.erb (Duration: 10523.6ms | Allocations: 18593781)
Completed 500 Internal Server Error in 10571ms (ActiveRecord: 4.7ms | Allocations: 18611819)


Not notifying due to an invalid api_key

ActionView::Template::Error (The asset 'tailwind.css' was not found in the load path.):
    35:     <!--<link href="https://fonts.googleapis.com/css?family=PT+Sans|Roboto+Mono&display=swap" rel="stylesheet">-->
    36:     <!--<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext" rel="stylesheet">-->
    37:     <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,500,700,800&display=swap" rel="stylesheet">
    38:     <%= stylesheet_link_tag "application", "tailwind", "inter-font", "data-turbo-track": "reload" %>
    39:     <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    40:   </head>
    41:

app/views/layouts/application.html.erb:38
```

**Comment by michelson** [comment]
You need to run the assets precompilation; in a new tab use `yarn dev.`
which installation guide are you following?

**Comment by michelson** [comment]
did it work?

**Comment by michelson** [comment]
feel free to reopen this if you have any problems regarding this issue.

**Comment by jesusalc** [comment]
no it did not work

**Comment by jesusalc** [comment]
<img width="1670" alt="Screenshot 2023-01-21 at 15 21 27" src="https://user-images.githubusercontent.com/1438028/213871099-ecc65294-9f4c-4c6c-8ca7-7cc3f5eedaa3.png">

yarn dev is running but still broken

**Comment by jesusalc** [comment]
<img width="1671" alt="Screenshot 2023-01-21 at 15 24 26" src="https://user-images.githubusercontent.com/1438028/213871221-88ef5c59-72d5-410b-a72d-075411d5b272.png">
yarn dev is running but still broken

**Comment by michelson** [comment]
can you stop the rails server, stop yarn dev, then start rails server and start yarn dev.

**Comment by jesusalc** [comment]
<img width="466" alt="Screenshot 2023-01-21 at 15 26 17" src="https://user-images.githubusercontent.com/1438028/213871273-f3a032f5-3160-4b5f-b55a-3c048532ea2f.png">
following these instructions here in this website

**Comment by michelson** [comment]
also, you could try, `./bin/dev` which run both commands in one

**Comment by jesusalc** [comment]
I tried first option, and error still persists

**Comment by jesusalc** [comment]
<img width="1669" alt="Screenshot 2023-01-21 at 15 29 55" src="https://user-images.githubusercontent.com/1438028/213871462-14d6b721-ecbe-471d-b051-5a1b9b76dfc3.png">
Now with foreman I get a new error and it does not load quite well

**Comment by michelson** [comment]
cool, now it is working. 
now you will need to setup the HOST and WS env vars to instruct chaskiq to render the panel. for example if you want to chaskiq works on 127.0.0.1:3000 then `HOST=http://127.0.0.1:3000` and `WS=ws://127.0.0.1:3000`

**Comment by jesusalc** [comment]
could it be "Not delivering sessions due to an invalid api_key" ?

**Comment by jesusalc** [comment]
inside .env ?

**Comment by michelson** [comment]
yes, and you will need to restart the server for it to pick the changes

**Comment by jesusalc** [comment]
<img width="552" alt="Screenshot 2023-01-21 at 15 35 27" src="https://user-images.githubusercontent.com/1438028/213871673-f3f1f085-99a2-4202-8303-e987f33bec72.png">
This is my current .env file

**Comment by jesusalc** [comment]
So it seems 
localhost is not the same as 127.0.0.1 or 0.0.0.0 which is kind of not cool  
<img width="1547" alt="Screenshot 2023-01-21 at 15 37 01" src="https://user-images.githubusercontent.com/1438028/213871834-0ad99499-c8dc-41b2-a1b7-35342879571f.png">


Now is loading login screen 

but password login is not working

**Comment by jesusalc** [comment]
<img width="611" alt="Screenshot 2023-01-21 at 15 51 18" src="https://user-images.githubusercontent.com/1438028/213872377-437a1184-eb73-4cd8-abd1-ba9b328172e6.png">
 rails admin_generator is not working to setup the admin password
 
 rails aborted!
NoMethodError: undefined method `add_admin' for nil:NilClass

**Comment by michelson** [comment]
can you try it with localhost instead 127.0.0.1 ?

**Comment by michelson** [comment]
> <img alt="Screenshot 2023-01-21 at 15 51 18" width="611" src="https://user-images.githubusercontent.com/1438028/213872377-437a1184-eb73-4cd8-abd1-ba9b328172e6.png">
> 
> rails admin_generator is not working to setup the admin password
> rails aborted! NoMethodError: undefined method `add_admin' for nil:NilClass

you need to run `rails db:seed` first
